import { boolean, date, integer, numeric, pgTable, serial, text, timestamp } from 'drizzle-orm/pg-core'

export const farmerProfiles = pgTable('farmer_profiles', {
  id: serial('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), village: text('village'), phone: text('phone'), language: text('language').notNull().default('ta'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
})
export const crops = pgTable('crops', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), variety: text('variety'), fieldName: text('field_name'), stage: text('stage').notNull().default('Planted'), plantedAt: date('planted_at'), health: text('health').notNull().default('Good'), notes: text('notes'), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const farmTasks = pgTable('farm_tasks', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), title: text('title').notNull(), dueDate: date('due_date'), priority: text('priority').notNull().default('Medium'), completed: boolean('completed').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
export const marketPrices = pgTable('market_prices', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), cropName: text('crop_name').notNull(), marketName: text('market_name').notNull(), pricePerQuintal: numeric('price_per_quintal', { precision: 10, scale: 2 }).notNull(), unit: text('unit').notNull().default('₹ / quintal'), trend: text('trend').notNull().default('Stable'), recordedAt: timestamp('recorded_at', { withTimezone: true }).defaultNow().notNull() })
export const governmentSchemes = pgTable('government_schemes', { id: serial('id').primaryKey(), userId: text('user_id').notNull(), name: text('name').notNull(), description: text('description'), benefit: text('benefit'), eligibility: text('eligibility'), deadline: date('deadline'), saved: boolean('saved').notNull().default(false), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() })
